name: Bug Report
description: Bug report template (EH)
title: "[Bug]: "
labels: [ "bug" ]
projects: [ ]
assignees: [ ]
body:
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      description: The Minecraft version you are using
      placeholder: "1.20.1"
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: The version of the mod you are using
      placeholder: "0.7.0-alpha.1"
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod Loader
      description: The mod loader you are using
      options:
        - Fabric
        - Forge
        - NeoForge
    validations:
      required: true
  - type: input
    id: mod-loader-version
    attributes:
      label: Mod Loader Version
      description: The version of your mod loader
      placeholder: "45.1.0"
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: GPU
      description: Your graphics card model
      placeholder: "NVIDIA GeForce RTX 3050"
  - type: input
    id: gpu-drivers-version
    attributes:
      label: GPU Driver Version
      description: Your graphics driver version
      placeholder: "560.94"
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
    validations:
      required: true
  - type: textarea
    id: crash-reports
    attributes:
      label: Crash Reports
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: For rendering/UI issues, please attach relevant screenshots
  - type: textarea
    id: mod-list
    attributes:
      label: Mod List
      description: Installed mods and their versions
    validations:
      required: true