name: Build and Upload Artifacts

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
      tag_name:
        description: "tag_name"
        required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        id: build
        if: ${{ !cancelled() }}
        run: python script/buildAll.py

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.tag_name }}
          token: ${{ secrets.TOKEN }}
          body_path: ./CHANGELOG.md
          files: |
            ./build_jars/**
            ./CHANGELOG.md